In [ ]:
!cutadapt -a GGCAAATGGGTTTTCAAGATCC...GGTANTGGANNTATGAATATTC --revcomp --overlap 18 -e 0.2 --discard-untrimmed --minimum-length 200 --maximum-length 450 --info-file data/cox2_th_cutadapt/cutadapt-info.tsv -o data/cox2_th_cutadapt/seq-trimmed_tmp.fasta data/cox2_th_cutadapt/seq-filtered.fasta

This is cutadapt 5.1 with Python 3.10.18
Command line parameters: -a GGCAAATGGGTTTTCAAGATCC...GGTANTGGANNTATGAATATTC --overlap 18 --revcomp -e 0.2 --discard-untrimmed --minimum-length 200 -o data/cut-test-require-both.fasta data/cox2_th/seq-filtered.fasta
Processing single-end reads on 1 core ...
Done           00:00:00         3,873 reads @ 198.6 µs/read;   0.30 M reads/minute

=== Summary ===

Total reads processed:                   3,873
Reads with adapters:                     3,859 (99.6%)
Reverse-complemented:                        0 (0.0%)

== Read fate breakdown ==
Reads that were too short:                 169 (4.4%)
Reads discarded as untrimmed:               14 (0.4%)
Reads written (passing filters):         3,690 (95.3%)

Total basepairs processed:     5,748,580 bp
Total written (filtered):      1,027,740 bp (17.9%)

=== Adapter 1 ===

Sequence: GGCAAATGGGTTTTCAAGATCC...GGTANTGGANNTATGAATATTC; Type: linked; Length: 22+22; 5' trimmed: 218 times; 3' trimmed: 3858 times; Reverse-complemented: 0 times

Minimum overlap: 18+18
No. of allowed errors:
1-4 bp: 0; 5-9 bp: 1; 10-14 bp: 2; 15-19 bp: 3; 20-22 bp: 4

No. of allowed errors:
1-4 bp: 0; 5-9 bp: 1; 10-14 bp: 2; 15-19 bp: 3

Overview of removed sequences at 5' end
length	count	expect	max.err	error counts
18	12	0.0	3	1 1 10
19	8	0.0	3	6 0 1 1
20	10	0.0	4	8 1 0 0 1
21	12	0.0	4	7 0 4 0 1
22	35	0.0	4	11 21 2 0 1
23	27	0.0	4	23 2 0 2
24	7	0.0	4	2 1 2 2
25	9	0.0	4	0 1 4 4
26	5	0.0	4	0 0 2 1 2
27	3	0.0	4	2 1
28	1	0.0	4	1
29	3	0.0	4	2 0 1
74	3	0.0	4	0 1 1 1
79	1	0.0	4	0 1
873	1	0.0	4	0 0 1
2377	1	0.0	4	0 0 1
4719	1	0.0	4	0 0 1
6543	1	0.0	4	0 0 0 1
6635	1	0.0	4	0 0 0 1
6648	1	0.0	4	0 0 1
6669	1	0.0	4	0 0 1
6688	1	0.0	4	0 0 1
6714	1	0.0	4	0 0 1
6818	1	0.0	4	0 0 1
6860	1	0.0	4	0 0 1
6889	1	0.0	4	0 0 1
6919	1	0.0	4	0 0 1
6931	1	0.0	4	0 0 1
6948	1	0.0	4	0 0 1
6993	1	0.0	4	0 0 1
7140	1	0.0	4	0 0 1
7142	1	0.0	4	0 0 1
7169	1	0.0	4	0 0 1
7175	1	0.0	4	0 0 1
7212	1	0.0	4	0 0 1
7258	1	0.0	4	0 0 1
7334	1	0.0	4	0 0 1
7609	1	0.0	4	0 0 1
7675	1	0.0	4	0 0 1
7696	1	0.0	4	0 0 1
7705	1	0.0	4	0 0 1
7710	1	0.0	4	0 0 1
7730	1	0.0	4	0 0 1
7740	1	0.0	4	0 0 1
8019	1	0.0	4	0 0 1
8050	1	0.0	4	0 0 1
8068	1	0.0	4	0 0 1
8111	1	0.0	4	0 0 1
8840	1	0.0	4	0 0 1
8919	1	0.0	4	0 0 1
8964	1	0.0	4	0 0 1
8967	1	0.0	4	0 0 1
8985	1	0.0	4	0 0 0 1
9043	1	0.0	4	0 0 1
9285	1	0.0	4	0 0 1
9868	1	0.0	4	0 0 1
10065	2	0.0	4	0 0 0 2
11616	1	0.0	4	0 0 0 1
12301	1	0.0	4	0 0 1
12390	1	0.0	4	0 0 1
13142	1	0.0	4	0 0 0 1
14657	1	0.0	4	0 0 1
17761	1	0.0	4	0 0 1
20752	1	0.0	4	0 0 1
24783	1	0.0	4	0 0 1
28832	1	0.0	4	0 0 0 1
29189	1	0.0	4	0 0 1
30037	1	0.0	4	0 0 1
31906	1	0.0	4	1
35383	1	0.0	4	0 0 1
36273	1	0.0	4	0 0 1
36590	1	0.0	4	0 0 1
36635	1	0.0	4	0 0 1
36664	1	0.0	4	0 0 1
36672	1	0.0	4	0 0 1
36928	1	0.0	4	0 0 1
37004	1	0.0	4	0 0 1
37268	1	0.0	4	0 0 1
37399	2	0.0	4	0 0 2
37421	1	0.0	4	0 0 1
37451	1	0.0	4	0 0 1
37469	2	0.0	4	0 0 2
37477	1	0.0	4	0 0 1
38820	1	0.0	4	0 0 1
39039	1	0.0	4	0 0 1
39080	1	0.0	4	0 0 1
39398	1	0.0	4	0 0 1
41827	1	0.0	4	0 0 1
43200	1	0.0	4	0 0 0 1
45385	1	0.0	4	0 1
46831	1	0.0	4	1
47260	1	0.0	4	0 1
50384	1	0.0	4	0 0 1



Overview of removed sequences at 3' end
length	count	expect	max.err	error counts
38	1	0.0	3	1
46	1	0.0	3	1
99	14	0.0	3	14
122	1	0.0	3	1
127	1	0.0	3	1
135	2	0.0	3	2
148	26	0.0	3	20 6
149	1	0.0	3	0 1
155	63	0.0	3	63
157	2	0.0	3	2
167	1	0.0	3	1
172	1	0.0	3	0 1
176	1	0.0	3	1
178	2	0.0	3	2
180	1	0.0	3	1
181	4	0.0	3	4
182	33	0.0	3	33
183	2	0.0	3	1 1
189	1	0.0	3	0 1
190	3	0.0	3	3
193	1	0.0	3	0 1
194	3	0.0	3	3
195	1	0.0	3	1
196	2	0.0	3	2
198	1	0.0	3	1
199	22	0.0	3	11 11
201	1	0.0	3	0 1
203	31	0.0	3	8 23
204	2	0.0	3	2
205	6	0.0	3	6
206	2	0.0	3	1 1
208	19	0.0	3	15 4
209	1	0.0	3	0 1
210	1	0.0	3	1
211	2	0.0	3	1 1
212	1	0.0	3	1
215	11	0.0	3	1 10
218	1	0.0	3	1
219	1	0.0	3	1
221	1	0.0	3	1
222	2	0.0	3	2
224	2	0.0	3	2
225	1	0.0	3	1
226	5	0.0	3	5
227	5	0.0	3	1 4
230	5	0.0	3	5
232	3	0.0	3	3
233	2	0.0	3	2
234	2	0.0	3	2
235	4	0.0	3	1 3
236	4	0.0	3	2 2
237	5	0.0	3	4 1
238	9	0.0	3	8 1
239	16	0.0	3	16
240	2	0.0	3	2
241	3	0.0	3	3
242	1	0.0	3	1
243	1	0.0	3	1
244	25	0.0	3	22 3
245	4	0.0	3	4
246	38	0.0	3	27 11
247	1	0.0	3	1
248	8	0.0	3	6 0 2
249	130	0.0	3	65 65
250	115	0.0	3	51 13 51
251	3	0.0	3	1 2
252	10	0.0	3	8 2
253	37	0.0	3	26 11
254	7	0.0	3	6 0 0 1
255	20	0.0	3	18 1 0 1
256	9	0.0	3	7 0 0 2
257	19	0.0	3	17 2
258	13	0.0	3	10 1 0 2
259	16	0.0	3	12 2 0 2
260	18	0.0	3	16 2
261	29	0.0	3	24 5
262	89	0.0	3	74 12 0 3
263	35	0.0	3	35
264	11	0.0	3	8 3
265	10	0.0	3	8 2
266	24	0.0	3	13 9 2
267	15	0.0	3	14 1
268	6	0.0	3	5 1
269	9	0.0	3	7 2
270	13	0.0	3	11 2
271	21	0.0	3	10 11
272	24	0.0	3	23 1
273	8	0.0	3	8
274	13	0.0	3	13
275	36	0.0	3	28 7 1
276	55	0.0	3	48 7
277	64	0.0	3	56 8
278	103	0.0	3	102 1
279	10	0.0	3	4 6
280	12	0.0	3	11 1
281	15	0.0	3	13 2
282	12	0.0	3	10 2
283	13	0.0	3	11 1 1
284	12	0.0	3	12
285	3	0.0	3	2 0 1
286	345	0.0	3	322 23
287	242	0.0	3	219 17 6
288	6	0.0	3	5 1
289	4	0.0	3	4
290	16	0.0	3	13 2 1
291	198	0.0	3	169 15 13 1
292	26	0.0	3	21 5
293	13	0.0	3	13
294	38	0.0	3	35 3
295	22	0.0	3	21 1
296	2	0.0	3	2
297	28	0.0	3	22 6
298	2	0.0	3	0 2
299	1	0.0	3	0 1
300	36	0.0	3	32 2 1 1
301	7	0.0	3	3 3 1
302	26	0.0	3	23 3
303	60	0.0	3	54 6
304	47	0.0	3	38 9
305	17	0.0	3	17
306	54	0.0	3	51 3
307	56	0.0	3	54 2
308	6	0.0	3	6
309	6	0.0	3	4 1 1
310	1	0.0	3	1
311	1	0.0	3	1
312	1	0.0	3	1
313	1	0.0	3	1
314	1	0.0	3	1
316	3	0.0	3	2 1
317	2	0.0	3	1 1
318	14	0.0	3	8 3 3
319	36	0.0	3	32 4
320	13	0.0	3	11 2
321	2	0.0	3	1 0 1
323	4	0.0	3	1 3
325	29	0.0	3	28 0 1
327	1	0.0	3	0 1
328	2	0.0	3	1 1
329	2	0.0	3	2
331	1	0.0	3	1
333	2	0.0	3	0 2
334	1	0.0	3	0 1
341	2	0.0	3	2
383	1	0.0	3	1
390	8	0.0	3	8
392	7	0.0	3	6 1
395	1	0.0	3	1
403	1	0.0	3	1
407	75	0.0	3	67 8
545	29	0.0	3	28 1
560	1	0.0	3	1
563	1	0.0	3	1
591	1	0.0	3	0 1
592	1	0.0	3	1
601	1	0.0	3	1
605	1	0.0	3	1
607	10	0.0	3	10
608	1	0.0	3	1
609	1	0.0	3	1
611	1	0.0	3	1
621	1	0.0	3	1
624	8	0.0	3	8
625	1	0.0	3	1
627	1	0.0	3	1
628	3	0.0	3	3
629	5	0.0	3	2 3
630	17	0.0	3	16 1
631	3	0.0	3	2 1
632	6	0.0	3	5 1
633	4	0.0	3	4
634	9	0.0	3	9
635	1	0.0	3	1
636	12	0.0	3	12
637	1	0.0	3	1
638	1	0.0	3	1
639	7	0.0	3	7
641	1	0.0	3	1
642	3	0.0	3	3
643	4	0.0	3	3 1
644	1	0.0	3	1
647	2	0.0	3	2
648	10	0.0	3	9 1
649	5	0.0	3	5
650	7	0.0	3	7
651	7	0.0	3	7
652	1	0.0	3	1
654	10	0.0	3	10
655	14	0.0	3	12 2
656	10	0.0	3	7 3
657	8	0.0	3	6 2
658	10	0.0	3	10
660	2	0.0	3	2
661	3	0.0	3	3
662	1	0.0	3	1
663	1	0.0	3	1
664	6	0.0	3	6
666	1	0.0	3	1
667	4	0.0	3	4
668	28	0.0	3	28
669	2	0.0	3	1 1
670	1	0.0	3	1
671	1	0.0	3	1
672	2	0.0	3	2
673	7	0.0	3	1 6
674	1	0.0	3	1
675	4	0.0	3	4
676	5	0.0	3	5
677	2	0.0	3	1 1
678	4	0.0	3	3 1
679	3	0.0	3	2 1
680	19	0.0	3	19
681	110	0.0	3	109 1
682	103	0.0	3	103
683	31	0.0	3	31
684	40	0.0	3	40
685	33	0.0	3	33
686	37	0.0	3	32 5
687	4	0.0	3	4
688	3	0.0	3	3
689	3	0.0	3	3
691	3	0.0	3	3
692	3	0.0	3	3
693	2	0.0	3	2
695	3	0.0	3	2 1
696	7	0.0	3	7
697	5	0.0	3	5
698	2	0.0	3	1 1
699	2	0.0	3	2
700	4	0.0	3	4
701	3	0.0	3	3
702	1	0.0	3	1
704	1	0.0	3	1
705	3	0.0	3	2 1
706	3	0.0	3	3
707	4	0.0	3	3 1
708	1	0.0	3	1
710	1	0.0	3	1
712	5	0.0	3	5
713	4	0.0	3	4
714	3	0.0	3	3
715	4	0.0	3	4
716	2	0.0	3	1 1
717	2	0.0	3	2
718	3	0.0	3	2 1
719	6	0.0	3	5 1
721	1	0.0	3	1
722	2	0.0	3	2
723	4	0.0	3	4
725	1	0.0	3	1
726	4	0.0	3	3 1
727	4	0.0	3	4
729	2	0.0	3	1 1
730	3	0.0	3	3
731	4	0.0	3	4
735	2	0.0	3	2
741	1	0.0	3	1
744	1	0.0	3	1
751	2	0.0	3	2
753	2	0.0	3	2
1240	1	0.0	3	0 0 1
1306	40	0.0	3	0 0 40
1318	3	0.0	3	0 0 3
1335	1	0.0	3	1
1342	1	0.0	3	0 0 1
1343	12	0.0	3	0 0 12
1380	4	0.0	3	0 0 4
1825	1	0.0	3	1
1827	1	0.0	3	0 0 1
1829	1	0.0	3	1
1836	1	0.0	3	1
1838	1	0.0	3	1
1839	2	0.0	3	2
1842	1	0.0	3	1
1843	1	0.0	3	1
1845	1	0.0	3	1
1849	1	0.0	3	1
1855	1	0.0	3	1
1870	1	0.0	3	0 0 1
1880	1	0.0	3	1
1934	1	0.0	3	1
1939	1	0.0	3	1
1940	1	0.0	3	1
2409	1	0.0	3	0 1
4315	1	0.0	3	1
10941	1	0.0	3	1
13724	1	0.0	3	1
14202	1	0.0	3	1
14335	1	0.0	3	1
14734	1	0.0	3	1
15567	1	0.0	3	1
17088	1	0.0	3	1
19923	1	0.0	3	1
24016	1	0.0	3	1
24283	1	0.0	3	1
26734	1	0.0	3	1
27696	1	0.0	3	1
27824	1	0.0	3	1
27826	1	0.0	3	1
27863	1	0.0	3	1
27875	1	0.0	3	1
28617	1	0.0	3	1
28978	1	0.0	3	1
29754	1	0.0	3	1
29793	1	0.0	3	0 1
29814	1	0.0	3	1
29872	1	0.0	3	1
29888	1	0.0	3	1
29894	1	0.0	3	1
29927	1	0.0	3	1
30069	1	0.0	3	1
30109	1	0.0	3	1
30264	1	0.0	3	0 1
30453	1	0.0	3	0 1
30485	1	0.0	3	1
30543	1	0.0	3	0 1
30580	1	0.0	3	1
30641	1	0.0	3	1
30738	1	0.0	3	1
30802	1	0.0	3	1
30830	1	0.0	3	1
30853	1	0.0	3	1
30915	1	0.0	3	1
30963	2	0.0	3	0 0 2
30968	1	0.0	3	1
31188	1	0.0	3	1
31278	1	0.0	3	1
31370	1	0.0	3	1
31503	1	0.0	3	1
31664	1	0.0	3	1
31715	1	0.0	3	1
31884	1	0.0	3	1
32324	1	0.0	3	1
32458	1	0.0	3	1
34982	1	0.0	3	1
36136	1	0.0	3	1
37158	1	0.0	3	0 1
37800	1	0.0	3	0 1
37899	1	0.0	3	0 1
37911	1	0.0	3	0 1
43725	1	0.0	3	0 1

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data/cox2_th_cutadapt/cutadapt-info.tsv', sep='\t', header=None)
df = df.drop(columns=[8, 9, 10])
df.columns = ['accession', 'errors', 'start', 'end', 'left_seq', 'primer_seq', 'right_seq', 'primer_name', 'reverse_complement']
df = df[df['errors'] != -1]
df['accession'] = df['accession'].str.replace(' rc', '')
df['reverse_complement'] = df['reverse_complement'].astype(bool)
df['start'] = df['start'].astype(int)
df['end'] = df['end'].astype(int)
df['primer_size'] = df['end'] - df['start']
df

,accession,errors,start,end,left_seq,primer_seq,right_seq,primer_name,reverse_complement,primer_size
0,PV995066.1,0,242,264,GTTTTTTTTAATTATTGTTACTGTATTTGTATGTTGGATGTTATTT...,GGTATTGGAGTTATGAATATTC,AGATAATTTAGAATTTTCTGATGAACCTTTAATTTTTGATAGTTAT...,1;2,False,22
1,PV995065.1,0,242,264,GTTTTTTTTAATTATTGTTACTGTATTTGTATGTTGGATGTTATTT...,GGTATTGGAGTTATGAATATTC,AGATAATTTAGAATTTTCTGATGAACCTTTAATTTTTGATAGTTAT...,1;2,False,22
2,PV995064.1,0,242,264,GTTTTTTTTAATTATTGTTACTGTATTTGTATGTTGGATGTTATTT...,GGTATTGGAGTTATGAATATTC,AGATAATTTAGAATTTTCTGATGAACCTTTAATTTTTGATAGTTAT...,1;2,False,22
3,PV956201.1,0,247,269,TTAATGTTTTTTTTAATTATCGTTACTGTATTTGTTTGTTGGATGT...,GGTACTGGAGTTATGAATATTC,CGATAATTTAGAATTTTCCGATGAACCTTTAATTTTCGATAGTTAT...,1;2,False,22
4,PV956200.1,0,290,312,AGCAACTCCAGTTATGGAAGGTATTATTAACTTTCATCATGATTTA...,GGTACTGGAGTTATGAATATTC,CGATAATTTAGAATTTTCCGATGAACCTTTAATTTTCGATAGTTAT...,1;2,False,22
...,...,...,...,...,...,...,...,...,...,...
4708,AB253782.1,1,284,306,TGCGACTCCTGTAATGGAAGGTATTATTAATTTTCATAATGACTTA...,GGTATTGGAGTTATGAATATAC,TGATAATTTTAATAATATTAATTTTGATAGTTATATGATTCCTACT...,1;2,False,22
4709,AB253781.1,1,284,306,TGCGACTCCTGTAATGGAAGGTATTATTAATTTTCATAATGACTTA...,GGTATTGGAGTTATGAATATAC,TGATAATTTTAATAATATTAATTTTGATAGTTATATGATTCCTACT...,1;2,False,22
4710,AB253780.1,1,284,306,TGCGACTCCTGTAATGGAAGGTATTATTAATTTTCATAATGACTTA...,GGTATTGGAGTTATGAATATAC,TGATAATTTTAATAATATTAATTTTGATAGCTATATGATTCCTACT...,1;2,False,22
4711,AY913800.1,1,291,313,TGCAACTCCACTGTATGGAAGGTATTATAAATTTTCATCATGATTT...,GGTTTTGGACTTATGAATATTC,AGATATTTTAAATTACTTTGATAAAAATGAAAATTTAATTTTTGAT...,1;2,False,22
4712,AJ890351.2,0,277,299,ATGGAAGGTATTATAAACTTTCACCATGATTTAATGTTTTTCTTAA...,GGTATTGGAGTTATGAATATTC,TGATAATTTAGAATTTGCTGATGAACCTTTAATTTTTGATAGTTAT...,1;2,False,22

In [3]:
# Example primer mapping (adjust if you have more than one pair)
primer_map = {"1;1": "forward", "1;2": "reverse"}

# Assign forward/reverse labels
df["primer_direction"] = df["primer_name"].map(primer_map)

# Pivot so forward/reverse get their own columns
wide = df.pivot_table(
    index="accession",
    columns="primer_direction",
    values=["errors", "start", "end", "left_seq", "primer_seq", "right_seq", "primer_name", 'primer_size'],
    aggfunc="first"  # avoids duplicates
)

# Flatten the MultiIndex column names
wide.columns = [f"{col[0]}_{col[1]}" for col in wide.columns]

# Reset index so accession is a normal column
wide = wide.reset_index()
wide = wide.drop_duplicates(subset="accession")

# Keep accession first, then all forward, then all reverse
ordered_cols = ["accession", "start_forward", "end_forward", "errors_forward", 'primer_size_forward', "primer_name_forward", "primer_seq_forward", "left_seq_forward", "right_seq_forward", "start_reverse", "end_reverse", 'primer_size_reverse', "errors_reverse", "primer_name_reverse", "primer_seq_reverse", "left_seq_reverse", "right_seq_reverse"]
wide = wide[ordered_cols]
wide = wide.merge(df[['accession', 'reverse_complement']], on='accession', how='inner')
wide = wide.drop_duplicates(subset="accession")

wide

,accession,start_forward,end_forward,errors_forward,primer_size_forward,primer_name_forward,primer_seq_forward,left_seq_forward,right_seq_forward,start_reverse,end_reverse,primer_size_reverse,errors_reverse,primer_name_reverse,primer_seq_reverse,left_seq_reverse,right_seq_reverse,reverse_complement
0,AB095053.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,287.0,309.0,22.0,0.0,1;2,GGTATTGGAGTTATGAATATTC,AACTCCAGTAATGGAAGGTATTATTAACTTTCATCATGATTTAATG...,CGATAATTTAGAATTTGCTGATGAACCTTTAATTTTTGATAGTTAT...,False
1,AB095054.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,287.0,309.0,22.0,0.0,1;2,GGTATTGGAGTTATGAATATTC,AACTCCAGTAATGGAAGGTATTATTAACTTTCATCATGATTTAATG...,CGATAATTTGGAATTTGCTGACGAACCTTTAATTTTTGATAGTTAT...,False
2,AB095055.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,287.0,309.0,22.0,0.0,1;2,GGTATTGGAGTTATGAATATTC,AACTCCAGTAATGGAAGGTATTATTAACTTTCATCATGATTTAATG...,CGATAATTTGGAATTTGCTGACGAACCTTTAATTTTTGATAGTTAT...,False
3,AB095056.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,287.0,309.0,22.0,0.0,1;2,GGTATTGGAGTTATGAATATTC,AACTCCAGTAATGGAAGGTATTATTAACTTTCATCATGATTTAATG...,CGATAATTTAGAATTTGCTGATGAACCTTTAATTTTTGATAGTTAT...,False
4,AB095057.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,287.0,309.0,22.0,1.0,1;2,GGTATTGGAGTTATGAGTATTC,AACACCTGTAATGGAAGGTATTATAAACTTTCATCATGATTTAATG...,TGATAATTTAGAATTCGCAGATGAACCTTTAATTTTTGATAGTTAT...,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4075,PV956200.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,290.0,312.0,22.0,0.0,1;2,GGTACTGGAGTTATGAATATTC,AGCAACTCCAGTTATGGAAGGTATTATTAACTTTCATCATGATTTA...,CGATAATTTAGAATTTTCCGATGAACCTTTAATTTTCGATAGTTAT...,False
4076,PV956201.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,247.0,269.0,22.0,0.0,1;2,GGTACTGGAGTTATGAATATTC,TTAATGTTTTTTTTAATTATCGTTACTGTATTTGTTTGTTGGATGT...,CGATAATTTAGAATTTTCCGATGAACCTTTAATTTTCGATAGTTAT...,False
4077,PV995064.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,242.0,264.0,22.0,0.0,1;2,GGTATTGGAGTTATGAATATTC,GTTTTTTTTAATTATTGTTACTGTATTTGTATGTTGGATGTTATTT...,AGATAATTTAGAATTTTCTGATGAACCTTTAATTTTTGATAGTTAT...,False
4078,PV995065.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,242.0,264.0,22.0,0.0,1;2,GGTATTGGAGTTATGAATATTC,GTTTTTTTTAATTATTGTTACTGTATTTGTATGTTGGATGTTATTT...,AGATAATTTAGAATTTTCTGATGAACCTTTAATTTTTGATAGTTAT...,False
4079,PV995066.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,242.0,264.0,22.0,0.0,1;2,GGTATTGGAGTTATGAATATTC,GTTTTTTTTAATTATTGTTACTGTATTTGTATGTTGGATGTTATTT...,AGATAATTTAGAATTTTCTGATGAACCTTTAATTTTTGATAGTTAT...,False

In [4]:
"""wide_copy = wide.copy()
wide_copy['start_reverse'] = wide_copy['start_reverse'].fillna(0)
wide_copy['end_forward'] = wide_copy['end_forward'].fillna(0)
wide_copy['amplicon_size'] = wide_copy['start_reverse'] - wide_copy['end_forward']
amplicon_size = wide_copy[['accession', 'amplicon_size']]
wide = wide.merge(amplicon_size, on='accession')
wide"""

"wide_copy = wide.copy()\nwide_copy['start_reverse'] = wide_copy['start_reverse'].fillna(0)\nwide_copy['end_forward'] = wide_copy['end_forward'].fillna(0)\nwide_copy['amplicon_size'] = wide_copy['start_reverse'] - wide_copy['end_forward']\namplicon_size = wide_copy[['accession', 'amplicon_size']]\nwide = wide.merge(amplicon_size, on='accession')\nwide"

In [5]:
both_primers = wide.dropna(subset=['primer_seq_forward', 'primer_seq_reverse']).copy()
# fix reverse primer position
both_primers['start_reverse'] = both_primers['end_forward'] + both_primers['start_reverse']
both_primers['end_reverse'] = both_primers['end_forward'] + both_primers['end_reverse']
both_primers

,accession,start_forward,end_forward,errors_forward,primer_size_forward,primer_name_forward,primer_seq_forward,left_seq_forward,right_seq_forward,start_reverse,end_reverse,primer_size_reverse,errors_reverse,primer_name_reverse,primer_seq_reverse,left_seq_reverse,right_seq_reverse,reverse_complement
416,DQ365699.1,2.0,23.0,1.0,21.0,1;1,GGCAAATGGGTTTCAAGATCC,TT,AGCTACACCTGTTATGGAAGGAATTATTAATTTTCACCACGATATT...,313.0,335.0,22.0,0.0,1;2,GGTACTGGAGTTATGAATATTC,AGCTACACCTGTTATGGAAGGAATTATTAATTTTCACCACGATATT...,AGATAATTTAGAATTTTCTGATGAACCTTTAATTTTTGATAGTTAT...,False
418,DQ365700.1,1.0,23.0,0.0,22.0,1;1,GGCAAATGGGTTTTCAAGATCC,T,AGCAACTCCAGTTATGGAAGGTATTATTAACTTTCATCATGATATA...,313.0,335.0,22.0,0.0,1;2,GGTATTGGAGTTATGAATATTC,AGCAACTCCAGTTATGGAAGGTATTATTAACTTTCATCATGATATA...,AGATAATTTAGAATTTTCAGATGAACCTTTAATTTTTGATAGTTAT...,False
420,DQ365702.1,1.0,22.0,1.0,21.0,1;1,GGCAAATGGGTTTCAAGATCC,T,TGCAACTCCAGTAATGGAAGGTATTATTAACTTTCATCATGATTTA...,312.0,334.0,22.0,0.0,1;2,GGTATTGGAGTTATGAATATTC,TGCAACTCCAGTAATGGAAGGTATTATTAACTTTCATCATGATTTA...,AGACAATTTAGAATTTTCAGATGAACCTTTAATTTTTGATAGTTAT...,False
424,DQ365705.1,1.0,22.0,1.0,21.0,1;1,GGCAAATGGGTTTCAAGATCC,T,AGCAACTCCAGTAATGGAAGGTATTATAAACTTTCATCATGATTTA...,312.0,334.0,22.0,0.0,1;2,GGTATTGGAGTTATGAATATTC,AGCAACTCCAGTAATGGAAGGTATTATAAACTTTCATCATGATTTA...,AGATAATTTAGAATTTTCAGATGAACCTTTAATTTTTGATAGTTAT...,False
426,DQ365706.1,0.0,22.0,0.0,22.0,1;1,GGCAAATGGGTTTTCAAGATCC,None,TGCAACTCCCGTTATGGAAGGTATTATTAACTTTCATCACGATTTA...,312.0,334.0,22.0,0.0,1;2,GGTATTGGAGTTATGAATATTC,TGCAACTCCCGTTATGGAAGGTATTATTAACTTTCATCACGATTTA...,AGATAATTTAGAATTTTCGGATGAACCTTTAATTTTTGATAGTTAT...,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4030,PV243791.1,36613.0,36635.0,2.0,22.0,1;1,GGCAATTAGGTTTTCAAGATCC,ATGAATTTTCAAAATATAAATAAATGGTCAACAAGATGGCTTTTTT...,AGCAACTCCCGTAATGGAAGGTATTATAAATTTTCATCATGATTTA...,36925.0,36947.0,22.0,0.0,1;2,GGTACTGGAGTTATGAATATTC,AGCAACTCCCGTAATGGAAGGTATTATAAATTTTCATCATGATTTA...,AGATAATTTAGAATTTTCTGATGAACCTTTAATTTTTGATAGTTAT...,False
4032,PV243795.1,37377.0,37399.0,2.0,22.0,1;1,GGCAATTAGGTTTTCAAGATCC,ATGAATTTTCAAAATATAAATAAATGGTCAACAAGATGGCTTTTTT...,AGCAACTCCAGTAATGGAAGGTATTATAAATTTTCATCATGATTTA...,37689.0,37711.0,22.0,0.0,1;2,GGTACTGGAGTTATGAATATTC,AGCAACTCCAGTAATGGAAGGTATTATAAATTTTCATCATGATTTA...,AGATAATTTAGAATTTTCTGATGAACCTTTAATTTTTGATAGTTAT...,False
4034,PV243796.1,37377.0,37399.0,2.0,22.0,1;1,GGCAATTAGGTTTTCAAGATCC,ATGAATTTTCAAAATATAAATAAATGGTCAACAAGATGGCTTTTTT...,AGCAACTCCAGTAATGGAAGGTATTATAAATTTTCATCATGATTTA...,37689.0,37711.0,22.0,0.0,1;2,GGTACTGGAGTTATGAATATTC,AGCAACTCCAGTAATGGAAGGTATTATAAATTTTCATCATGATTTA...,AGATAATTTAGAATTTTCTGATGAACCTTTAATTTTTGATAGTTAT...,False
4036,PV243803.1,39017.0,39039.0,2.0,22.0,1;1,GGCAATTAGGTTTTCAAGATCC,ATGAATTTTCAAAATATAAATAAATGGTCAACAAGATGGCTTTTTT...,AGCAACTCCAGTTATGGAAGGTATTATAAACTTTCATCATGATTTA...,39329.0,39351.0,22.0,0.0,1;2,GGTATTGGAGTTATGAATATTC,AGCAACTCCAGTTATGGAAGGTATTATAAACTTTCATCATGATTTA...,AGATAATTTAGAATTTTCTGATGAACCTTTAATTTTTGATAGTTAT...,False
4038,PV243804.1,39058.0,39080.0,2.0,22.0,1;1,GGCAATTAGGTTTTCAAGATCC,ATGAATTTTCAAAATATAAATAAATGGTCAACAAGATGGCTTTTTT...,AGCAACTCCAGTTATGGAAGGTATTATAAACTTTCACCATGATTTA...,39370.0,39392.0,22.0,0.0,1;2,GGTATTGGAGTTATGAATATTC,AGCAACTCCAGTTATGGAAGGTATTATAAACTTTCACCATGATTTA...,AGATAATTTAGAATTTTCTGATGAACCTTTAATTTTTGATAGTTAT...,False

In [6]:
final_db = pd.read_csv('data/cox2_th_cutadapt/cox2_th_cutadapt-meta.csv', sep='\t')
final_db

,accession,creation_date,title,authors,sequence_length,organism_name,tax_id_x,organism,organelle,mol_type,...,trimed_seq_len,tax_id_y,species,domain,kingdom,phylum,class,order,family,genus
0,MW006635.1,23-NOV-2020,Globisporangium irregulare isolate UM1087 cyto...,"Callaghan,S.E.",621,Globisporangium irregulare,36331,Globisporangium irregulare,mitochondrion,genomic DNA,...,315,36331,Globisporangium irregulare,Eukaryota,Stramenopiles,Oomycota,Peronosporomycetes,Pythiales,Pythiaceae,Globisporangium
1,KM819519.1,27-JAN-2015,Pythiogeton ramosum isolate SC2.7.2 cytochrome...,"Le,D.P., Smith,M.K. and Aitken,E.",614,Pythiogeton ramosum,1217586,Pythiogeton ramosum,mitochondrion,genomic DNA,...,307,1217586,Pythiogeton ramosum,Eukaryota,Stramenopiles,Oomycota,Peronosporomycetes,Pythiales,Pythiogetonaceae,Pythiogeton
2,LC028397.1,01-NOV-2016,Pythium barbulae mitochondrial cox2 gene for c...,"Ueta,S. and Tojo,M.",613,Globisporangium barbulae,1629122,Globisporangium barbulae,mitochondrion,genomic DNA,...,306,1629122,Globisporangium barbulae,Eukaryota,Stramenopiles,Oomycota,Peronosporomycetes,Pythiales,Pythiaceae,Globisporangium
3,KP723171.1,16-SEP-2015,Globisporangium kandovanense voucher CCTU 1813...,"Chenari Bouket,A., Arzanlou,M., Tojo,M. and Ba...",587,Globisporangium kandovanense,1632203,Globisporangium kandovanense,mitochondrion,genomic DNA,...,301,1632203,Globisporangium kandovanense,Eukaryota,Stramenopiles,Oomycota,Peronosporomycetes,Pythiales,Pythiaceae,Globisporangium
4,GU071804.1,25-JUL-2016,Pythium irregulare strain STE-U6769 cytochrome...,"Spies,C.F., Mazzola,M., Botha,W.J., Langenhove...",596,Globisporangium irregulare,36331,Globisporangium irregulare,mitochondrion,genomic DNA,...,299,36331,Globisporangium irregulare,Eukaryota,Stramenopiles,Oomycota,Peronosporomycetes,Pythiales,Pythiaceae,Globisporangium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1281,MK602199.1,29-APR-2020,Globisporangium spinosum isolate C9 cytochrome...,"Ibanez,J.M., Obregon,V.G. and Favaro,M.A.",518,Globisporangium spinosum,2125998,Globisporangium spinosum,mitochondrion,genomic DNA,...,211,2125998,Globisporangium spinosum,Eukaryota,Stramenopiles,Oomycota,Peronosporomycetes,Pythiales,Pythiaceae,Globisporangium
1282,MK602203.1,29-APR-2020,Globisporangium irregulare isolate C13 cytochr...,"Ibanez,J.M., Obregon,V.G. and Favaro,M.A.",518,Globisporangium irregulare,36331,Globisporangium irregulare,mitochondrion,genomic DNA,...,211,36331,Globisporangium irregulare,Eukaryota,Stramenopiles,Oomycota,Peronosporomycetes,Pythiales,Pythiaceae,Globisporangium
1283,MK602204.1,29-APR-2020,Globisporangium irregulare isolate C14 cytochr...,"Ibanez,J.M., Obregon,V.G. and Favaro,M.A.",518,Globisporangium irregulare,36331,Globisporangium irregulare,mitochondrion,genomic DNA,...,211,36331,Globisporangium irregulare,Eukaryota,Stramenopiles,Oomycota,Peronosporomycetes,Pythiales,Pythiaceae,Globisporangium
1284,MK602213.1,29-APR-2020,Globisporangium irregulare isolate C24 cytochr...,"Ibanez,J.M., Obregon,V.G. and Favaro,M.A.",518,Globisporangium irregulare,36331,Globisporangium irregulare,mitochondrion,genomic DNA,...,211,36331,Globisporangium irregulare,Eukaryota,Stramenopiles,Oomycota,Peronosporomycetes,Pythiales,Pythiaceae,Globisporangium
1285,KP420744.1,14-JUN-2015,Anisolpidium ectocarpii isolate An_PM_76_6 cyt...,"Gachon,C.M.M. and Mueller,D.G.",451,Anisolpidium ectocarpii,1663100,Anisolpidium ectocarpii,mitochondrion,genomic DNA,...,205,1663100,Anisolpidium ectocarpii,Eukaryota,Stramenopiles,Oomycota,incertae sedis,Anisolpidiales,Anisolpidiaceae,Anisolpidium

In [ ]:
primers_in_db = both_primers[both_primers['accession'].isin(final_db['accession'])].copy()
#primers_in_db = primers_in_db.set_index('accession')
primers_in_db

,accession,start_forward,end_forward,errors_forward,primer_size_forward,primer_name_forward,primer_seq_forward,left_seq_forward,right_seq_forward,start_reverse,end_reverse,primer_size_reverse,errors_reverse,primer_name_reverse,primer_seq_reverse,left_seq_reverse,right_seq_reverse,reverse_complement
424,DQ365705.1,1.0,22.0,1.0,21.0,1;1,GGCAAATGGGTTTCAAGATCC,T,AGCAACTCCAGTAATGGAAGGTATTATAAACTTTCATCATGATTTA...,312.0,334.0,22.0,0.0,1;2,GGTATTGGAGTTATGAATATTC,AGCAACTCCAGTAATGGAAGGTATTATAAACTTTCATCATGATTTA...,AGATAATTTAGAATTTTCAGATGAACCTTTAATTTTTGATAGTTAT...,False
426,DQ365706.1,0.0,22.0,0.0,22.0,1;1,GGCAAATGGGTTTTCAAGATCC,None,TGCAACTCCCGTTATGGAAGGTATTATTAACTTTCATCACGATTTA...,312.0,334.0,22.0,0.0,1;2,GGTATTGGAGTTATGAATATTC,TGCAACTCCCGTTATGGAAGGTATTATTAACTTTCATCACGATTTA...,AGATAATTTAGAATTTTCGGATGAACCTTTAATTTTTGATAGTTAT...,False
429,DQ365708.1,1.0,22.0,1.0,21.0,1;1,GGCAAATGGGTTTCAAGATCC,T,AGCAACTCCCGTAATGGAAGGTATTATAAACTTTCATCACGATTTA...,312.0,334.0,22.0,0.0,1;2,GGTACTGGAGTTATGAATATTC,AGCAACTCCCGTAATGGAAGGTATTATAAACTTTCATCACGATTTA...,CGATAATTTAGAATTTTCTGATGAACCTTTAATTTTTGATAGTTAT...,False
432,DQ365710.1,1.0,22.0,1.0,21.0,1;1,GGCAAATGGGTTTCAAGATCC,T,AGCAACCCCTGTAATGGAAGGTATTATCAATTTTCATCACGATTTA...,312.0,334.0,22.0,0.0,1;2,GGTATTGGAGTTATGAATATTC,AGCAACCCCTGTAATGGAAGGTATTATCAATTTTCATCACGATTTA...,GGATAATTTAGAATTTTCAGATGAACCTTTAATTTTTGATAGTTAT...,False
435,DQ365712.1,4.0,25.0,1.0,21.0,1;1,GGCAAATGGGTTTCAAGATCC,CCTT,TGCAACACCCGTGATGGAGGGTATTATTAATTTCCACCACGATATT...,315.0,337.0,22.0,1.0,1;2,GGTATTGGAGTTACGAATATTC,TGCAACACCCGTGATGGAGGGTATTATTAATTTCCACCACGATATT...,GGATAATTTAGAATTTTCAGATGAACCTCTGATCTTTGATAGTTAT...,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4024,PV243786.1,37447.0,37469.0,2.0,22.0,1;1,GGCAATTAGGTTTTCAAGATCC,ATGAATTTTCAAAATATAAATAAATGGTCAACAAGATGGCTTTTTT...,AGCAACTCCTGTAATGGAAGGTATTATAAATTTTCATCATGATTTA...,37759.0,37781.0,22.0,0.0,1;2,GGTATTGGAGCTATGAATATTC,AGCAACTCCTGTAATGGAAGGTATTATAAATTTTCATCATGATTTA...,AGATAATTTAGAATTTTCAGATGAACCTTTAATTTTTGATAGTTAT...,False
4030,PV243791.1,36613.0,36635.0,2.0,22.0,1;1,GGCAATTAGGTTTTCAAGATCC,ATGAATTTTCAAAATATAAATAAATGGTCAACAAGATGGCTTTTTT...,AGCAACTCCCGTAATGGAAGGTATTATAAATTTTCATCATGATTTA...,36925.0,36947.0,22.0,0.0,1;2,GGTACTGGAGTTATGAATATTC,AGCAACTCCCGTAATGGAAGGTATTATAAATTTTCATCATGATTTA...,AGATAATTTAGAATTTTCTGATGAACCTTTAATTTTTGATAGTTAT...,False
4034,PV243796.1,37377.0,37399.0,2.0,22.0,1;1,GGCAATTAGGTTTTCAAGATCC,ATGAATTTTCAAAATATAAATAAATGGTCAACAAGATGGCTTTTTT...,AGCAACTCCAGTAATGGAAGGTATTATAAATTTTCATCATGATTTA...,37689.0,37711.0,22.0,0.0,1;2,GGTACTGGAGTTATGAATATTC,AGCAACTCCAGTAATGGAAGGTATTATAAATTTTCATCATGATTTA...,AGATAATTTAGAATTTTCTGATGAACCTTTAATTTTTGATAGTTAT...,False
4036,PV243803.1,39017.0,39039.0,2.0,22.0,1;1,GGCAATTAGGTTTTCAAGATCC,ATGAATTTTCAAAATATAAATAAATGGTCAACAAGATGGCTTTTTT...,AGCAACTCCAGTTATGGAAGGTATTATAAACTTTCATCATGATTTA...,39329.0,39351.0,22.0,0.0,1;2,GGTATTGGAGTTATGAATATTC,AGCAACTCCAGTTATGGAAGGTATTATAAACTTTCATCATGATTTA...,AGATAATTTAGAATTTTCTGATGAACCTTTAATTTTTGATAGTTAT...,False
4038,PV243804.1,39058.0,39080.0,2.0,22.0,1;1,GGCAATTAGGTTTTCAAGATCC,ATGAATTTTCAAAATATAAATAAATGGTCAACAAGATGGCTTTTTT...,AGCAACTCCAGTTATGGAAGGTATTATAAACTTTCACCATGATTTA...,39370.0,39392.0,22.0,0.0,1;2,GGTATTGGAGTTATGAATATTC,AGCAACTCCAGTTATGGAAGGTATTATAAACTTTCACCATGATTTA...,AGATAATTTAGAATTTTCTGATGAACCTTTAATTTTTGATAGTTAT...,False

In [8]:
from Bio import SeqIO

In [9]:
accessions = primers_in_db['accession'].tolist()
records = [record for record in SeqIO.parse('data/cox2_th_cutadapt/seq-filtered.fasta', 'fasta') if record.id in accessions]

primer_size = 22

with open('align-full-amplicon.fasta', 'w') as out:
    for record in records:
        row = primers_in_db.loc[primers_in_db['accession'] == record.id]
        if row['reverse_complement'].bool():
            record.seq = record.seq.reverse_complement()
        start = int(row['start_forward'])
        end = int(row['end_reverse'])
        if start != 0 and int(row['primer_size_forward']) < primer_size:
            start = max(0, int(row['end_forward']) - primer_size)
        if end != len(record.seq) and int(row['primer_size_reverse']) < primer_size:
            end = min(len(record.seq), int(row['start_reverse']) + primer_size)
        out.write(f">REF_{record.id}\n{str(record.seq)[start:end]}\n")

/tmp/ipykernel_3959991/1779096869.py:9: FutureWarning: Series.bool is now deprecated and will be removed in future version of pandas
  if row['reverse_complement'].bool():
/tmp/ipykernel_3959991/1779096869.py:11: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  start = int(row['start_forward'])
/tmp/ipykernel_3959991/1779096869.py:12: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  end = int(row['end_reverse'])
/tmp/ipykernel_3959991/1779096869.py:13: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  if start != 0 and int(row['primer_size_forward']) < primer_size:
/tmp/ipykernel_3959991/1779096869.py:15: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  if end != len(record.seq) and int(row['primer_size_reverse']) < primer_size:
/tmp/ipykernel_3959991/1779096869.py:14: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  start = max(0, int(row['end_forward']) - primer_size)

In [ ]:
from Bio import AlignIO

records = AlignIO.read('data/cox2_th_cutadapt/cox2_th_cutadapt-qiime-msa.fa', 'fasta')

firsts = []
lasts = []


for record in list(records):
    if record.id not in accessions:
        continue
    seq = str(record.seq)
    # find first non-gap
    first = next(i for i, base in enumerate(seq) if base != "-")
    # find last non-gap
    last = len(seq) - next(i for i, base in enumerate(reversed(seq)) if base != "-") - 1
    firsts.append(first)
    lasts.append(last)
firsts = pd.Series(firsts)
lasts = pd.Series(lasts)
# trim at most frequent position among the reference sequences
trim_start = int(firsts.value_counts(sort=True, ascending=False).index[0])
trim_end = int(lasts.value_counts(sort=True, ascending=False).index[0])

In [17]:
# slice alignment: [rows, columns]
trimmed = records[:, trim_start:trim_end + 1]
AlignIO.write(trimmed, "trimmed_alignment.fasta", "fasta")

1