In [1]:
import pandas as pd
from src import database

In [2]:
df = pd.read_csv('data/seq-meta.csv')
df

,accession,creation_date,title,authors,sequence,sequence_length,organism_name,tax_id,cox2_start,cox2_end,cox2_strand
0,JF414552.1,12-DEC-2013,Pseudoperonospora cubensis isolate CDM-274 cyt...,"Mitchell,M.N., Ocamb,C.M., Grunwald,N.J., Manc...",GAACCTTGGCAATTAGGTTTTCAAGATCCTGCAACTCCCGTTATGG...,2164,Pseudoperonospora cubensis,143453,<0,726,1.0
1,JF414551.1,12-DEC-2013,Pseudoperonospora cubensis isolate CDM-273 cyt...,"Mitchell,M.N., Ocamb,C.M., Grunwald,N.J., Manc...",GAACCTTGGCAATTAGGTTTTCAAGATCCTGCAACTCCCGTTATGG...,2164,Pseudoperonospora cubensis,143453,<0,726,1.0
2,JF414550.1,12-DEC-2013,Pseudoperonospora cubensis isolate CDM-272 cyt...,"Mitchell,M.N., Ocamb,C.M., Grunwald,N.J., Manc...",GAACCTTGGCAATTAGGTTTTCAAGATCCTGCAACTCCCGTTATGG...,2164,Pseudoperonospora cubensis,143453,<0,726,1.0
3,JF414549.1,12-DEC-2013,Pseudoperonospora cubensis isolate CDM-269 cyt...,"Mitchell,M.N., Ocamb,C.M., Grunwald,N.J., Manc...",GAACCTTGGCAATTAGGTTTTCAAGATCCTGCAACTCCCGTTATGG...,2164,Pseudoperonospora cubensis,143453,<0,726,1.0
4,JF414548.1,12-DEC-2013,Pseudoperonospora cubensis isolate CDM-268 cyt...,"Mitchell,M.N., Ocamb,C.M., Grunwald,N.J., Manc...",GAACCTTGGCAATTAGGTTTTCAAGATCCTGCAACTCCCGTTATGG...,2164,Pseudoperonospora cubensis,143453,<0,726,1.0
...,...,...,...,...,...,...,...,...,...,...,...
8507,OR094655.1,28-AUG-2023,Peronospora belbahrii isolate p15-1 cytochrome...,"Wang,C.-F. and Hong,C.-F.",AAGATCCAGCAACTCCAGTTATGGAAGGTATTATTAACTTTCACCA...,564,Peronospora belbahrii,622444,<0,>564,1.0
8508,OR094654.1,28-AUG-2023,Peronospora belbahrii isolate p14-1-1 cytochro...,"Wang,C.-F. and Hong,C.-F.",AAGATCCAGCAACTCCAGTTATGGAAGGTATTATTAACTTTCACCA...,600,Peronospora belbahrii,622444,<0,>600,1.0
8509,OR094653.1,28-AUG-2023,Peronospora belbahrii isolate p13-1 cytochrome...,"Wang,C.-F. and Hong,C.-F.",CAAGATCCAGCAACTCCAGTTATGGAAGGTATTATTAACTTTCACC...,564,Peronospora belbahrii,622444,<0,>564,1.0
8510,OR094652.1,28-AUG-2023,Peronospora belbahrii isolate p12-1 cytochrome...,"Wang,C.-F. and Hong,C.-F.",AAGATCCAGCAACTCCAGTTATGGAAGGTATTATTAACTTTCACCA...,601,Peronospora belbahrii,622444,<0,>601,1.0
8511,OR094651.1,28-AUG-2023,Peronospora belbahrii isolate p11-1 cytochrome...,"Wang,C.-F. and Hong,C.-F.",TTATGGAAGGTATTATTAACTTTCACCATGATTTAATGTTTTTTTT...,541,Peronospora belbahrii,622444,<0,>541,1.0

In [3]:
filtered = database.filter_data(df)
filtered

,accession,creation_date,title,authors,sequence,sequence_length,organism_name,tax_id,cox2_start,cox2_end,cox2_strand,organism_name_sanitized,tax_id_sanitized
16,JF414536.1,12-DEC-2013,Pseudoperonospora celtidis isolate SMK17780 cy...,"Mitchell,M.N., Ocamb,C.M., Grunwald,N.J., Manc...",GAACCTTGGCAATTAGGTTTTCAAGATCCTGCAACTCCCGTTATGG...,2162,Pseudoperonospora celtidis,291623,<0,726,1.0,Pseudoperonospora celtidis,291623
17,HM635956.1,12-DEC-2013,Pseudoperonospora cannabina isolate NY409 cyto...,"Runge,F., Choi,Y.-J. and Thines,M.",CAGCAACTCCCGTTATGGAAGGTATTATAAACTTTCATCATGATTT...,550,Pseudoperonospora cannabina,291622,<0,>550,1.0,Pseudoperonospora cannabina,291622
18,HM635955.1,12-DEC-2013,Pseudoperonospora cannabina isolate U181 cytoc...,"Runge,F., Choi,Y.-J. and Thines,M.",CAGCAACTCCCGTTATGGAAGGTATTATAAACTTTCATCATGATTT...,550,Pseudoperonospora cannabina,291622,<0,>550,1.0,Pseudoperonospora cannabina,291622
20,HM635953.1,12-DEC-2013,Pseudoperonospora urticae isolate PDD1 cytochr...,"Runge,F., Choi,Y.-J. and Thines,M.",CAGCAACTCCCGTTATGGAAGGTATTATTAACTTTCATCATGATTT...,550,Pseudoperonospora urticae,162119,<0,>550,1.0,Pseudoperonospora urticae,162119
21,HM635952.1,12-DEC-2013,Pseudoperonospora urticae isolate HOH1111 cyto...,"Runge,F., Choi,Y.-J. and Thines,M.",CGGCAACTCCCGTTATGGAAGGTATTATTAACTTTCATCATGATTT...,550,Pseudoperonospora urticae,162119,<0,>550,1.0,Pseudoperonospora urticae,162119
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8479,LC730894.1,31-AUG-2023,Aphanomyces iridis CK14D1 mitochondrial cox2 g...,"Kageyama,K., Watanabe,H., Otsubo,K., Suga,H. a...",ATGGAAGGAATTATAAATTTTCATCATGATTTAGTTTTTTTTTTAG...,552,Aphanomyces iridis,601994,<0,>552,1.0,Aphanomyces iridis,601994
8480,LC730893.1,31-AUG-2023,Aphanomyces iridis CK12DI1 mitochondrial cox2 ...,"Kageyama,K., Watanabe,H., Otsubo,K., Suga,H. a...",ATGGAAGGAATTATAAATTTTCATCATGATTTAGTTTTTTTTTTAG...,552,Aphanomyces iridis,601994,<0,>552,1.0,Aphanomyces iridis,601994
8482,LC730891.1,31-AUG-2023,Aphanomyces cochlioides MAFF 305845 mitochondr...,"Kageyama,K., Watanabe,H., Otsubo,K., Suga,H. a...",ATGGAAGGAATTATAAATTTTCATCATGATTTAGTTTTTTTTTTAG...,552,Aphanomyces cochlioides,112091,<0,>552,1.0,Aphanomyces cochlioides,112091
8483,LC730890.1,31-AUG-2023,Aphanomyces cladogamus NBRC 103816 mitochondri...,"Kageyama,K., Watanabe,H., Otsubo,K., Suga,H. a...",ATGGAAGGAATTATAAATTTTCATCATGATTTATTTTTTTTTTTAG...,552,Aphanomyces cladogamus,253176,<0,>552,1.0,Aphanomyces cladogamus,253176
8484,LC730888.1,31-AUG-2023,Aphanomyces cladogamus MAFF 242268 mitochondri...,"Kageyama,K., Watanabe,H., Otsubo,K., Suga,H. a...",ATGGAAGGAATTATAAATTTTCATCATGATTTATTTTTTTTTTTAG...,552,Aphanomyces cladogamus,253176,<0,>552,1.0,Aphanomyces cladogamus,253176

In [4]:
trimmed = database.trim(filtered)

In [5]:
rev_comp = database.reverse_complement(trimmed)

In [6]:
rev_comp.to_csv('data/cox2-db-filtered.csv', sep='\t', index=False)

In [7]:
database.export_fasta_no_tax(rev_comp, 'data/cox2-db-filtered.fa')

In [ ]:
trimmed = database.import_fasta_no_tax(filtered, 'data/trimmed_filtered.fasta')
trimmed.to_csv('data/trimmed.csv', index=False)