In [1]:
import pandas as pd
from src import database, request, taxonomy
import re
from bs4 import BeautifulSoup
import asyncio

In [2]:
df = pd.read_csv('data/cox2_th_cutadapt/cox2_th_cutadapt-meta.csv', sep='\t')
df

,accession,creation_date,title,authors,sequence_length,organism_name,tax_id_x,organism,organelle,mol_type,...,trimed_seq_len,tax_id_y,species,domain,kingdom,phylum,class,order,family,genus
0,MW006635.1,23-NOV-2020,Globisporangium irregulare isolate UM1087 cyto...,"Callaghan,S.E.",621,Globisporangium irregulare,36331,Globisporangium irregulare,mitochondrion,genomic DNA,...,315,36331,Globisporangium irregulare,Eukaryota,Stramenopiles,Oomycota,Peronosporomycetes,Pythiales,Pythiaceae,Globisporangium
1,PP444835.1,14-MAR-2024,Peronosclerospora maydis isolate Tabanan cytoc...,"Sugiarta,D., Susanta Wirya,G.A. and Agung Phab...",346,Peronosclerospora maydis,886949,Peronosclerospora maydis,mitochondrion,genomic DNA,...,308,886949,Peronosclerospora maydis,Eukaryota,Stramenopiles,Oomycota,Peronosporomycetes,Peronosporales,Peronosporaceae,Peronosclerospora
2,OP727296.1,11-NOV-2023,Peronosclerospora neglecta culture BRIP:71135 ...,"Muis,A., Ryley,M.J., Tan,Y.P., Suharjo,R., Non...",409,Peronosclerospora neglecta,3090892,Peronosclerospora neglecta,mitochondrion,genomic DNA,...,227,3090892,Peronosclerospora neglecta,Eukaryota,Stramenopiles,Oomycota,Peronosporomycetes,Peronosporales,Peronosporaceae,Peronosclerospora
3,KM819519.1,27-JAN-2015,Pythiogeton ramosum isolate SC2.7.2 cytochrome...,"Le,D.P., Smith,M.K. and Aitken,E.",614,Pythiogeton ramosum,1217586,Pythiogeton ramosum,mitochondrion,genomic DNA,...,307,1217586,Pythiogeton ramosum,Eukaryota,Stramenopiles,Oomycota,Peronosporomycetes,Pythiales,Pythiogetonaceae,Pythiogeton
4,DQ071412.1,22-JUL-2009,Phytophthora megasperma strain CH95 cytochrome...,"Villa,N.O., Kageyama,K., Asano,T. and Suga,H.",563,Phytophthora megasperma,4788,Phytophthora megasperma,mitochondrion,genomic DNA,...,277,4788,Phytophthora megasperma,Eukaryota,Stramenopiles,Oomycota,Peronosporomycetes,Peronosporales,Peronosporaceae,Phytophthora
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1292,MK602199.1,29-APR-2020,Globisporangium spinosum isolate C9 cytochrome...,"Ibanez,J.M., Obregon,V.G. and Favaro,M.A.",518,Globisporangium spinosum,2125998,Globisporangium spinosum,mitochondrion,genomic DNA,...,211,2125998,Globisporangium spinosum,Eukaryota,Stramenopiles,Oomycota,Peronosporomycetes,Pythiales,Pythiaceae,Globisporangium
1293,MK602203.1,29-APR-2020,Globisporangium irregulare isolate C13 cytochr...,"Ibanez,J.M., Obregon,V.G. and Favaro,M.A.",518,Globisporangium irregulare,36331,Globisporangium irregulare,mitochondrion,genomic DNA,...,211,36331,Globisporangium irregulare,Eukaryota,Stramenopiles,Oomycota,Peronosporomycetes,Pythiales,Pythiaceae,Globisporangium
1294,MK602204.1,29-APR-2020,Globisporangium irregulare isolate C14 cytochr...,"Ibanez,J.M., Obregon,V.G. and Favaro,M.A.",518,Globisporangium irregulare,36331,Globisporangium irregulare,mitochondrion,genomic DNA,...,211,36331,Globisporangium irregulare,Eukaryota,Stramenopiles,Oomycota,Peronosporomycetes,Pythiales,Pythiaceae,Globisporangium
1295,MK602213.1,29-APR-2020,Globisporangium irregulare isolate C24 cytochr...,"Ibanez,J.M., Obregon,V.G. and Favaro,M.A.",518,Globisporangium irregulare,36331,Globisporangium irregulare,mitochondrion,genomic DNA,...,211,36331,Globisporangium irregulare,Eukaryota,Stramenopiles,Oomycota,Peronosporomycetes,Pythiales,Pythiaceae,Globisporangium
1296,KP420744.1,14-JUN-2015,Anisolpidium ectocarpii isolate An_PM_76_6 cyt...,"Gachon,C.M.M. and Mueller,D.G.",451,Anisolpidium ectocarpii,1663100,Anisolpidium ectocarpii,mitochondrion,genomic DNA,...,205,1663100,Anisolpidium ectocarpii,Eukaryota,Stramenopiles,Oomycota,incertae sedis,Anisolpidiales,Anisolpidiaceae,Anisolpidium

In [ ]:
hosts = pd.Series(df['host'].dropna().unique())
hosts = hosts.str.replace(r'\(.*\)', '', regex=True)
hosts = hosts.str.replace('  ', ' ')
hosts = hosts.apply(database.sanitize_org_name)
def to_genus(name: str) -> str:
    parts = name.split(' ')[:2]
    # remove non-alphabetical characters
    parts = list(map(lambda x: re.sub(r'[^a-zA-Z]', '', x), parts))
    if len(parts) == 2 and (parts[1] == 'sp' or parts[1] == 'spp'):
        return parts[0]
    return ' '.join(parts)
hosts = hosts.apply(to_genus)
hosts = pd.Series(hosts.unique()).astype(str)
hosts

0      Solanum lycopersicum
1                  Zea mays
2                       dog
3           Brassica juncea
4                    citrus
               ...
401       Knautia sylvatica
402        Anemone nemorosa
403       Fragaria ananassa
404       Citrullus lanatus
405                 Eustoma
Length: 406, dtype: object

In [4]:
client = request.HttpClient()

tax_ids = {}

for species in hosts:
    await asyncio.sleep(0.1)
    response = await client.esearch(species, 'taxonomy')
    id = None
    if response.result_count > 0:
        bs = BeautifulSoup(response.text_response, features="xml")
        id = int(bs.find('Id').string)
    tax_ids[species] = id

host_df = pd.DataFrame({'organism_name': hosts})
host_df

            organism_name
0    Solanum lycopersicum
1                Zea mays
2                     dog
3         Brassica juncea
4                  citrus
..                    ...
401     Knautia sylvatica
402      Anemone nemorosa
403     Fragaria ananassa
404     Citrullus lanatus
405               Eustoma

[406 rows x 1 columns]

In [5]:
#host_df = pd.DataFrame(tax_ids)
tax_ids

{'Solanum lycopersicum': 4081,
 'Zea mays': 4577,
 'dog': 9615,
 'Brassica juncea': 3707,
 'citrus': 2706,
 'Barbula unguiculata': 96465,
 'Oryza sativa': 4530,
 'Anoectochilus roxburghii': 569774,
 'Chenopodium album': 3559,
 'Cancrinia discoidea': 99082,
 'Semiaquilegia adoxoides': 349366,
 'Rhododendron': 4346,
 'Malus': 3749,
 'Lepidium sativum': 33125,
 'Panax notoginseng': 44586,
 'cacao': 3641,
 'Eruca vesicaria': 180536,
 'Sisymbrium': 3729,
 'Isatis': 161755,
 'Cinnamomum aromaticum': 119260,
 'Sarga leiocladum': 91527,
 'Sorghum plumosum': 143049,
 'Spinacia oleracea': 3562,
 'Atriplex patula': 3551,
 'Atriplex littoralis': 543010,
 'Atriplex prostrata': 190330,
 'Beta vulgaris': 161934,
 'Spergula arvensis': 325515,
 'Spergularia rubra': 157641,
 'Polycarpon diphyllum': 431019,
 'Rumex acetosella': 61450,
 'Chenopodium bonushenricus': None,
 'Erucastrum nasturtiifolium': 308294,
 'Manihot': 3982,
 'Sinapis arvensis': 2982281,
 'Lepidium campestre': 65351,
 'Plantago aristata': 197795,
 'Petrorhagia prolifera': 746822,
 'Cardamine impatiens': 82286,
 'Medicago sativa': 3879,
 'Buddleja brasiliensis': None,
 'Spinacea oleracea': 3562,
 'Papaver somniferum': 3469,
 'Ligularia fischeri': 186954,
 'Stellaria alsine': 254021,
 'Myosoton aquaticum': 228244,
 'Stellaria media': 13274,
 'Pseudostellaria palibiniana': 1137891,
 'Chenopodium quinoa': 63459,
 'Amaranthus blitum': 338571,
 'Eranthis hyemalis': 37492,
 'Cardamine circaeoides': 1049919,
 'Potentilla anserina': 57926,
 'Potentilla reptans': 57933,
 'Rubus caesius': 75065,
 'Nandina domestica': 41776,
 'Amaranthus dubius': 1193840,
 'Portulaca': 3582,
 'Stevia rebaudiana': 55670,
 'Amaranthus viridis': 56196,
 'Tragopogon porrifolius': 13731,
 'Eustoma exaltatum': 84884,
 'Cirsium oleraceum': 297476,
 'Luffa cylindrica': None,
 'Takhtajaniantha pusilla': 261629,
 'Symphyotrichum novaeangliae': 55612,
 'Eucalyptus badjensis': 929594,
 'Eucalyptus marginata': 183836,
 'Eucalyptus drummondii': 930108,
 'Cucumis sativus': 3659,
 'Vigna unguiculata': 3917,
 'Beaucarnea': 39517,
 'Banksia': 83698,
 'Hibbertia': 92929,
 'Banksia prionotes': 199789,
 'Xanthorrhoea platyphylla': 488790,
 'Rubus idaeus': 32247,
 'Casuarina obesa': 159616,
 'Pseudotsuga menziesii': 3357,
 'Armoracia rusticana': 3704,
 'ginger with': None,
 'Digitalis purpurea': 4164,
 'native bushland': None,
 'teaplant': None,
 'Salvia officinalis': 38868,
 'Cenchrus americanus': 4543,
 'Saccharum': 4546,
 'sugarcane': 128810,
 'Miscanthus japonicus': 154761,
 'Eriochloa pseudoacrotricha': None,
 'Enneapogon cylindricus': 1055019,
 'Enneapogon polyphyllus': 416044,
 'Aristida hygrometrica': 798301,
 'Eriochloa procera': 2057669,
 'Sorghum intrans': 143048,
 'Sorghum timorense': 91528,
 'Sehima nervosum': 796781,
 'Miscanthus sinensis': 62337,
 'Eruca sativa': 29727,
 'Claytonia perfoliata': 46146,
 'Pisum sativum': 3888,
 'Sonchus oleraceus': 50207,
 'Ischaemum fragile': None,
 'artichoke': 59895,
 'corn': 381124,
 'Lampranthus': 188832,
 'Celtis occidentalis': 228587,
 'Urtica dioica': 3501,
 'Cannabis sativa': 3483,
 'Neopyropia yezoensis': 2788,
 'Phellodendron amurense': 68554,
 'Xiphenema pachaicum': None,
 'Cleome anomala': 310220,
 'Capparis spinosa': 65558,
 'Capparis': 13394,
 'Boerhavia coccinea': 122400,
 'Ipomoea hederacea': 43178,
 'Portulaca oleracea': 46147,
 'Achyranthes japonicus': None,
 'Sisymbrium leteum': None,
 'Erigeron canadensis': 72917,
 'Iva xanthiifolia': 1447767,
 'Arthraxon hispidus': 330157,
 'Cardamine pratensis': 50465,
 'Plantago major': 29818,
 'Galium aparine': 29788,
 'Galium odoratum': 35899,
 'Geranium pusillum': 122182,
 'Ranunculus acris': 3447,
 'Cerastium holosteoides': 271563,
 'Tragopogon orientalis': 261649,
 'Amaranthus': 3564,
 'Iresine diffusa': 217685,
 'Berula erecta': 54827,
 'Celtis sinensis': 63053,
 'Cardamine diphylla': 109597,
 'Cardamine laciniata': 558124,
 'Cardamine bulbifera': 82356,
 'Cardamine heptaphylla': 558121,
 'Cardamine pentaphyllos': 82288,
 'Cardamine leucantha': 558126,
 'Cardamine enneaphyllos': 416611,
 'Cardamine graeca': 352368,
 'Cardamine flexuosa': 50462,
 'equine': 9796,
 'Papaver apulum': 357463,
 'Papaver rhoeas': 33128,
 'Papaver argemone': 357464,
 'Oenothera biennis': 3942,
 'Corydalis cava': 581246,
 'Chrysosplenium alternifolium': 80774,
 'Geranium molle': 581251,
 'Corydalis solida': 38914,
 'Papaver hybridum': 357471,
 'Holosteum umbellatum': 325497,
 'Lamium purpureum': 53164,
 'Meconopsis cambrica': 248829,
 'Papaver pavoninum': 357473,
 'Ranunculus repens': 137665,
 'Scrophularia nodosa': 90363,
 'Amaranthus powellii': 158579,
 'Capsella bursapastoris': 3719,
 'Scorzonera hispanica': 114289,
 'Tanacetum vulgare': 128002,
 'Rumex acetosa': 41241,
 'Anemone ranunculoides': 168005,
 'Saccharum officinarum': 4547,
 'nematode': 6231,
 'Centaurea cyanus': 41522,
 'Cirsium arvense': 41550,
 'Crepis mollis': 268022,
 'Lapsana communis': 268080,
 'Picris hieracioides': 212690,
 'Senecio vulgaris': 76276,
 'Sonchus arvensis': 50192,
 'Taraxacum officinale': 50225,
 'Lactuca indica': 75953,
 'Ixeris chinensis': 318058,
 'Youngia japonica': 89039,
 'Hemisteptia lyrata': None,
 'Bassia scoparia': 83154,
 'Cerastium semidecandrum': 271564,
 'Lipandra polysperma': 434244,
 'Consolida regalis': 984867,
 'Corydalis intermedia': 54425,
 'Dipsacus fullonum': 183561,
 'Erodium cicutarium': 301481,
 'Euphorbia cyparissias': 38844,
 'Euphorbia esula': 3993,
 'Euphrasia stricta': 691775,
 'Fumaria officinalis': 200993,
 'Glechoma hederacea': 28509,
 'Knautia arvensis': 105271,
 'Lathyrus pratensis': 254779,
 'Linaria genistifolia': 309346,
 'Linaria vulgaris': 43171,
 'Medicago lupulina': 47085,
 'Melilotus albus': 47082,
 'Mentha aquatica': 190902,
 'Moehringia trinervia': 169227,
 'Myosotis arvensis': 192338,
 'Polygonum aviculare': 137693,
 'Potentilla sterilis': 644184,
 'Ficaria verna': 79245,
 'Ranunculus sardous': 35930,
 'Saxifraga granulata': 83409,
 'Scabiosa ochroleuca': 596816,
 'Honckenya peploides': 169223,
 'Scleranthus annuus': 230712,
 'Cerastium brachypetalum': 271568,
 'Scutellaria galericulata': 53169,
 'Securigera varia': 53861,
 'Sherardia arvensis': 29803,
 'Silene noctiflora': 39899,
 'Spergula morisonii': 1351832,
 'Stachys palustris': 1060938,
 'Stellaria holostea': 581250,
 'Teucrium botrys': 1209845,
 'Trifolium dubium': 97021,
 'Trifolium medium': 97028,
 'Trifolium pratense': 57577,
 'Trifolium repens': 3899,
 'Tripleurospermum maritimum': 669858,
 'Urtica urens': 473050,
 'Verbascum nigrum': 90364,
 'Vicia hirsuta': 3910,
 'Viola arvensis': 97415,
 'Cerastium glomeratum': 3580,
 'Misopates orontium': 102599,
 'Alchemilla vulgaris': 49855,
 'Arenaria serpyllifolia': 254029,
 'Astragalus penduliflorus': 158323,
 'Cerastium dubium': 271581,
 'Chaenorhinum minus': 105913,
 'Galium mollugo': 254777,
 'Buglossoides arvensis': 181181,
 'Sanguisorba officinalis': 137457,
 'Trifolium hybridum': 74517,
 'Valeriana officinalis': 19953,
 'Verbena officinalis': 79772,
 'Elsholtzia ciliata': 662901,
 'Potentilla supina': 667287,
 'Salvia plebeia': 424424,
 'Atriplex': 3550,
 'Ranunculus illyricus': 286917,
 'Dicentra canadensis': 581247,
 'Conyza canadensis': 72917,
 'Carlina acaulis': 538471,
 'Centaurea phrygia': 910632,
 'Cirsium rivulare': 1532346,
 'Senecio inaequidens': 58524,
 'Centaurea jacea': 351340,
 'Cirsium vulgare': 92907,
 'Sonchus asper': 50193,
 'Crepidiastrum denticulatum': 77561,
 'Hemistepta lyrata': None,
 'Arabis': 50451,
 'Spergularia marina': 191669,
 'Eragrostis': 38413,
 'Agrimonia eupatoria': 57912,
 'Homo sapiens': 9606,
 'Descurainia pinnata': 110556,
 'Saposhnikovia divaricata': 203717,
 'Forcipomyia marksae': None,
 'Matricaria chamomilla': 98504,
 'Onobrychis cristagalli': None,
 'Malcolmia grandiflora': 1980597,
 'Chamaedorea seifrizii': 77339,
 'Vicia sativa': 3908,
 'Idesia polycarpa': 77057,
 'Melanthera integrifolia': 2596874,
 'Myosurus minimus': 59993,
 'Austropotamobius pallipes': 94943,
 'Plecoglossus altivelis': 61084,
 'Areca catechu': 184783,
 'Nicotiana tabacum': 4097,
 'Iseilema laxum': 2752325,
 'Plantago lagopus': 185001,
 'Cardamine concatenata': 109596,
 'Pylaiella littoralis': 2885,
 'Amaranthus retroflexus': 124763,
 'Plantago virginica': 113209,
 'Plantago rhodosperma': 223179,
 'Plantago patagonica': 197815,
 'Brassica oleracea': 3712,
 'Camelina sativa': 90675,
 'Descurainia sophia': 89411,
 'Diptychocarpus strictus': 359840,
 'Draba nemorosa': 171822,
 'Lepidium virginicum': 59292,
 'Lepidium': 19205,
 'Harmsiodoxa blennodioides': 913019,
 'Rapistrum rugosum': 71362,
 'Lepidium desvauxii': 153336,
 'Cardamine amara': 50461,
 'Cardamine hirsuta': 50463,
 'Reseda alba': 28546,
 'Rorippa': 50495,
 'Vicia sepium': 347188,
 'Valerianella carinata': 2952830,
 'Trigonotis peduncularis': 203766,
 'Draba hirta': 311934,
 'Allium cepa': 4679,
 'Crepidiastrum sonchifolium': 77563,
 'Arabidopsis arenosa': 38785,
 'Arabidopsis thaliana': 3702,
 'Fallopia convolvulus': 76029,
 'maize': 381124,
 'rice': 4530,
 'Mentha arvensis': 292239,
 'Brassica carinata': 52824,
 'Brassica rapa': 3711,
 'Brassica nigra': 3710,
 'Ornamental rai': None,
 'Circium arvense': None,
 'Brassica napus': 3708,
 'Persea americana': 3435,
 'Sinapis alba': 3728,
 'Vicia cracca': 3905,
 'Convolvulus gortschakovii': 2069597,
 'Chenopodium ficifolium': 887860,
 'Echium vulgare': 34253,
 'Tanacetum cinerariifolium': 118510,
 'Actinidia deliciosa': 3627,
 'Pachira aquatica': 69118,
 'soybean': 3847,
 'Gerbera jamesonii': 13547,
 'potato': 4113,
 'Citrus sinensis': 2711,
 'Pseudotsugae menziessi': None,
 'Prunus': 3754,
 'almond': 3755,
 'Glycine max': 3847,
 'Cinchona officinalis': 273781,
 'Quercus': 3511,
 'Carthamus tinctorius': 4222,
 'Asparagus officinalis': 4686,
 'Quercus agrifolia': 97693,
 'Chrysanthemum frutescens': 99032,
 'avocado': 3435,
 'Cyperus esculentus': 1053340,
 'Citrus Japonica': 76966,
 'Acacia mearnsii': 139012,
 'Pistacia vera': 55513,
 'Celosia argentea': 46112,
 'Iris hollandica': 35876,
 'Cryptotaenia japonica': 48117,
 'Lactuca sativa': 4236,
 'Salangichthys microdon': 137522,
 'Pelodiscus sinensis': 13735,
 'Chamaecyparis obtusa': 13415,
 'Carica papaya': 3649,
 'Aristotelia chilensis': 138855,
 'spinach': 3562,
 'Schizachyrium fragile': 883142,
 'lettuce': None,
 'Chrysanthemum': 13422,
 'Agrostis palustris': 62759,
 'Sanionia uncinata': 140003,
 'Echinacea angustifolia': 308558,
 'rice plant': None,
 'Lettuce Butterhead': None,
 'Prunus dulcis': 3755,
 'Corylus avellana': 13451,
 'Satureja hortensis': 49987,
 'Anagallis foemina': 357596,
 'Coleus scutellarioides': 4142,
 'Viburnum plicatum': 179996,
 'Phaseolus vulgaris': 3885,
 'Arctotis': 41477,
 'Perilla frutescens': 48386,
 'Ixeris polycephala': 502135,
 'Siegesbeckia glabrescens': 371450,
 'Lamium amplexicaule': 53160,
 'Tragopogon pratensis': 41653,
 'Aegopodium podagraria': 40902,
 'Symphytum tuberosum': 256504,
 'Turritis glabra': 63678,
 'Raphanus sativus': 3726,
 'Rorippa indica': 50499,
 'Rorippa palustris': 50498,
 'Thlaspi arvense': 13288,
 'Lathyrus japonicus': 154493,
 'Dysphania ambrosioides': 330163,
 'Clinopodium vulgare': 204222,
 'Zingiber officinale': 94328,
 'canine': None,
 'Salvia pratensis': 49216,
 'moribund simuliid': None,
 'Agrostemma githago': 39848,
 'Macadamia integrifolia': 60698,
 'Eragrostis cilianensis': 48734,
 'Triticum aestivum': 4565,
 'Perotis rara': 110901,
 'Amaranthus spinosus': 124765,
 'Ageratum conyzoides': 68299,
 'Galinsoga parviflora': 176602,
 'Veronicastrum virginicum': 165346,
 'Asparagopsis armata': 31367,
 'Vinca major': 185238,
 'Conyza': 41552,
 'Knautia sylvatica': None,
 'Anemone nemorosa': 37489,
 'Fragaria ananassa': 3747,
 'Citrullus lanatus': 3654,
 'Eustoma': 52517}

In [ ]:
async def fetch_lineage(taxids):
    lineage_data = {}
    
    # Batch into groups of ~200 IDs
    batch_size = 50
    taxids = [str(id) for id in taxids if id is not None]
    for i in range(0, len(taxids), batch_size):
        batch = taxids[i:i+batch_size]
        response = await client._client.get(f'{client._base_url}efetch.fcgi', params={
            'db': 'taxonomy',
            "id": ",".join(batch),
            "retmode": "xml",
            "rettype": "text"
        })
        response.raise_for_status()
        with open(f'data/cox2_db_cutadapt-meta-{i}.xml', 'w') as f:
            f.write(response.text)
        await asyncio.sleep(0.1)

    return lineage_data
lineage_data = await fetch_lineage(list(tax_ids.values()))
lineage_data

{}

In [2]:
taxonomy.parse_taxonomy('data/cox2_db_cutadapt-meta-0.xml', 'data/cox2_db_cutadapt-meta-0.csv')

In [3]:
await taxonomy.from_organsim_names(df['host'], 'data/cox2_th_cutadapt/host-tax-{}.xml', 'data/cox2_th_cutadapt/host-tax.csv')