In [1]:
import csv
from src import genbank_parser

In [2]:
with open('data/seq-meta.csv', 'w', newline='') as csv_file:
    csv_writer = csv.writer(csv_file)
    genbank_parser.dataclass_to_csv_header(csv_writer, genbank_parser.ParsedRecord)
    genbank_parser.parse_genbank_file('data/download/cox2_th_cutadapt.gb', csv_writer)

In [7]:
import pandas as pd
import json

In [ ]:
df = pd.read_csv('data/seq-meta.csv', index_col='accession')
df['metadata'] = df['metadata'].apply(json.loads)

df

,creation_date,title,authors,sequence,sequence_length,organism_name,tax_id,cox2_start,cox2_end,cox2_strand,metadata
accession,,,,,,,,,,,
PV995066.1,02-AUG-2025,Peronospora choii isolate 10896-3 cytochrome o...,"Marin,M.V., Sollazzo,C. and Peres,N.",GTTTTTTTTAATTATTGTTACTGTATTTGTATGTTGGATGTTATTT...,496,Peronospora choii,3056838,<0,>496,1.0,"{'organism': ['Peronospora choii'], 'organelle..."
PV995065.1,02-AUG-2025,Peronospora choii isolate 10896-2 cytochrome o...,"Marin,M.V., Sollazzo,C. and Peres,N.",GTTTTTTTTAATTATTGTTACTGTATTTGTATGTTGGATGTTATTT...,496,Peronospora choii,3056838,<0,>496,1.0,"{'organism': ['Peronospora choii'], 'organelle..."
PV995064.1,02-AUG-2025,Peronospora choii isolate 10896-1 cytochrome o...,"Marin,M.V., Sollazzo,C. and Peres,N.",GTTTTTTTTAATTATTGTTACTGTATTTGTATGTTGGATGTTATTT...,496,Peronospora choii,3056838,<0,>496,1.0,"{'organism': ['Peronospora choii'], 'organelle..."
PV942093.1,02-AUG-2025,Bremia sp. IK-2025a voucher FR-0046185 cytochr...,"Kontos,I., Choi,Y.-J. and Thines,M.",GGGTTTTCAAGATCCAGCAACTCCGGTAATGGAGGGTATCATTAAC...,625,Bremia sp. IK-2025a,3449784,<0,>625,1.0,"{'organism': ['Bremia sp. IK-2025a'], 'organel..."
PV942092.1,02-AUG-2025,Bremia sp. IK-2025a voucher FR-0046187 cytochr...,"Kontos,I., Choi,Y.-J. and Thines,M.",GGGTTTTCAAGATCCAGCAACTCCGGTAATGGAGGGTATCATTAAC...,625,Bremia sp. IK-2025a,3449784,<0,>625,1.0,"{'organism': ['Bremia sp. IK-2025a'], 'organel..."
...,...,...,...,...,...,...,...,...,...,...,...
AB253782.1,23-JUL-2016,Haptoglossa heterospora mitochondrial cox2 gen...,"Hakariya,M., Hirose,D. and Tokumasu,S.",TGCGACTCCTGTAATGGAAGGTATTATTAATTTTCATAATGACTTA...,563,Haptoglossa heterospora,377434,<0,>563,1.0,"{'organism': ['Haptoglossa heterospora'], 'org..."
AB253781.1,23-JUL-2016,Haptoglossa heterospora mitochondrial cox2 gen...,"Hakariya,M., Hirose,D. and Tokumasu,S.",TGCGACTCCTGTAATGGAAGGTATTATTAATTTTCATAATGACTTA...,563,Haptoglossa heterospora,377434,<0,>563,1.0,"{'organism': ['Haptoglossa heterospora'], 'org..."
AB253780.1,23-JUL-2016,Haptoglossa heterospora mitochondrial cox2 gen...,"Hakariya,M., Hirose,D. and Tokumasu,S.",TGCGACTCCTGTAATGGAAGGTATTATTAATTTTCATAATGACTTA...,563,Haptoglossa heterospora,377434,<0,>563,1.0,"{'organism': ['Haptoglossa heterospora'], 'org..."
AY913800.1,24-JUL-2006,Albugo trianthemae voucher DAR72457 cytochrome...,"Choi,Y.J., Hong,S.B. and Shin,H.D.",TGCAACTCCACTGTATGGAAGGTATTATAAATTTTCATCATGATTT...,561,Albugo trianthemae,323849,<0,>561,1.0,"{'organism': ['Albugo trianthemae'], 'organell..."
AJ890351.2,26-JUL-2016,Pythium phragmitis mitochondrial partial coxii...,"Nechwatal,J., Wielgoss,A. and Mendgen,K.",ATGGAAGGTATTATAAACTTTCACCATGATTTAATGTTTTTCTTAA...,563,Pythium phragmitis,319040,<0,>563,1.0,"{'organism': ['Pythium phragmitis'], 'organell..."

In [11]:

new_df = pd.DataFrame(df['metadata'].tolist(), index=df.index)
new_df

,organism,organelle,mol_type,cultivar,isolate,isolation_source,host,db_xref,geo_loc_name,collection_date,...,type_material,variety,clone,tissue_type,haplotype,submitter_seqid,cell_line,environmental_sample,bio_material,mating_type
accession,,,,,,,,,,,,,,,,,,,,,
PV995066.1,[Peronospora choii],[mitochondrion],[genomic DNA],[Avignon Early Blue],[10896-3],[Leaf:Downy mildew],[Lavandula angustifolia],[taxon:3056838],[USA: Florida],[2025],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PV995065.1,[Peronospora choii],[mitochondrion],[genomic DNA],[Avignon Early Blue],[10896-2],[Leaf:Downy mildew],[Lavandula angustifolia],[taxon:3056838],[USA: Florida],[2025],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PV995064.1,[Peronospora choii],[mitochondrion],[genomic DNA],[Avignon Early Blue],[10896-1],[Leaf:Downy mildew],[Lavandula angustifolia],[taxon:3056838],[USA: Florida],[2025],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PV942093.1,[Bremia sp. IK-2025a],[mitochondrion],[genomic DNA],NaN,NaN,NaN,[Scorzoneroides autumnalis],[taxon:3449784],[Iceland],[27-Sep-2024],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PV942092.1,[Bremia sp. IK-2025a],[mitochondrion],[genomic DNA],NaN,NaN,NaN,[Scorzoneroides autumnalis],[taxon:3449784],[Iceland],[08-Oct-2024],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
AB253782.1,[Haptoglossa heterospora],[mitochondrion],[genomic DNA],NaN,NaN,NaN,NaN,[taxon:377434],[Japan:Tokyo],NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AB253781.1,[Haptoglossa heterospora],[mitochondrion],[genomic DNA],NaN,NaN,[soil],NaN,[taxon:377434],[Japan: Nagano],NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AB253780.1,[Haptoglossa heterospora],[mitochondrion],[genomic DNA],NaN,NaN,[soil],NaN,[taxon:377434],[Japan: Tokyo],NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AY913800.1,[Albugo trianthemae],[mitochondrion],[genomic DNA],NaN,NaN,NaN,[Lampranthus sp. cult.],[taxon:323849],NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AJ890351.2,[Pythium phragmitis],[mitochondrion],[genomic DNA],NaN,NaN,NaN,NaN,[taxon:319040],[Germany:Lake of Konstanz],NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
# Remove single-element lists
def unwrap_single_element(x):
    if isinstance(x, list) and len(x) == 1:
        return x[0]
    return x

# Apply it across the whole DataFrame
new_df = new_df.applymap(unwrap_single_element)
new_df

/tmp/ipykernel_2171752/3770115057.py:8: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  new_df = new_df.applymap(unwrap_single_element)

,organism,organelle,mol_type,cultivar,isolate,isolation_source,host,db_xref,geo_loc_name,collection_date,...,type_material,variety,clone,tissue_type,haplotype,submitter_seqid,cell_line,environmental_sample,bio_material,mating_type
accession,,,,,,,,,,,,,,,,,,,,,
PV995066.1,Peronospora choii,mitochondrion,genomic DNA,Avignon Early Blue,10896-3,Leaf:Downy mildew,Lavandula angustifolia,taxon:3056838,USA: Florida,2025,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PV995065.1,Peronospora choii,mitochondrion,genomic DNA,Avignon Early Blue,10896-2,Leaf:Downy mildew,Lavandula angustifolia,taxon:3056838,USA: Florida,2025,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PV995064.1,Peronospora choii,mitochondrion,genomic DNA,Avignon Early Blue,10896-1,Leaf:Downy mildew,Lavandula angustifolia,taxon:3056838,USA: Florida,2025,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PV942093.1,Bremia sp. IK-2025a,mitochondrion,genomic DNA,NaN,NaN,NaN,Scorzoneroides autumnalis,taxon:3449784,Iceland,27-Sep-2024,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PV942092.1,Bremia sp. IK-2025a,mitochondrion,genomic DNA,NaN,NaN,NaN,Scorzoneroides autumnalis,taxon:3449784,Iceland,08-Oct-2024,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
AB253782.1,Haptoglossa heterospora,mitochondrion,genomic DNA,NaN,NaN,NaN,NaN,taxon:377434,Japan:Tokyo,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AB253781.1,Haptoglossa heterospora,mitochondrion,genomic DNA,NaN,NaN,soil,NaN,taxon:377434,Japan: Nagano,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AB253780.1,Haptoglossa heterospora,mitochondrion,genomic DNA,NaN,NaN,soil,NaN,taxon:377434,Japan: Tokyo,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AY913800.1,Albugo trianthemae,mitochondrion,genomic DNA,NaN,NaN,NaN,Lampranthus sp. cult.,taxon:323849,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AJ890351.2,Pythium phragmitis,mitochondrion,genomic DNA,NaN,NaN,NaN,NaN,taxon:319040,Germany:Lake of Konstanz,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN